### ISSUE TITLE
"Last Start" and "Last Success" for Tasks

### ISSUE THREAD

**Issue by sergeyka** [furier/websync#29]
On the "Tasks" view, is it possible to show for each task:
- "Last start" - date/time of latest rsync run attempt start
- "Last Success" date/time of latest successful rsync finish

This way the Tasks view will actually become a report where it will be easy to check:
- that tasks are not missing their schedule
- tasks are finishing successfully 
- the time every task takes 

Thank you!

**Comment by furier** [comment]
Great suggestions @sergeyka! :)
