### ISSUE TITLE
Docker container not transient

### ISSUE THREAD

**Issue by peterrus** [furier/websync#31]
Because the configuration of the application is not managed through a volume, every time you recreate the container, all configuration is lost. This breaks one of the basics of containerization, and in practicality is just not that great, because I tend to recreate my container when migrating servers or pulling in a new version of the image.

I'm not entirely familiar with websync yet, but there must be some configuration database or file that can be put in a volume.

**Comment by furier** [comment]
You are correct, there is a file and it could be put in a volume.

**Comment by peterrus** [comment]
I am trying to get websync to run on my pc, in order to try writing a more robust dockerfile. But for some reason npm/'node-gyp rebuild' keeps recompiling modules (I'm not experienced with node).

this happens on ubuntu 14.04 with nodejs 0.12.7 and earlier versions as well.

Any pointers?

**Comment by peterrus** [comment]
I am now stuck at #12

**Comment by peterrus** [comment]
configuration seems to be persisted across container lifetimes when running the container in the following way:

```
sudo docker run -d -p 3000:3000 -v /data-2/backup/fisheye:/fisheye -v /srv/data/websync.json:/src/wsdata.json -w /src furier/websync node server.js
```

**Comment by peterrus** [comment]
I am now trying to build the container just to test a very small change to the dockerfile, I am wondering, if you have time, if you could make this change for me, it has been quite a hassle to get a build environment working.

The change I am trying to make is:

Add the 'node server.js' startup command at the end of the file (WORKDIR /src) and (CMD node server.js)

Thanks in advance!

**Comment by furier** [comment]
I am unsure what you want me to do here, in the [Dockerfile](https://github.com/furier/websync/blob/master/Dockerfile#L31) I start `/src/server.js` with `node` as parameters for the `CMD` command.

you want me to set it as this?

    WORKDIR /src
    CMD ["node", "server.js"]

**Comment by peterrus** [comment]
You are totally right, my bad, so if I understand correctly there is no need to specify 'node server.js' in the docker startup command? (as you state in the README.MD).

**Comment by furier** [comment]
What readme.md is that? :P

tir. 5. jan. 2016 kl. 18.52 skrev peterrus <notifications@github.com>:

**Comment by peterrus** [comment]
https://github.com/furier/websync/blob/master/README.md line 63
