### ISSUE TITLE
Can't install on ubuntu 12.04 lts

### ISSUE THREAD

**Issue by ZalemCitizen** [furier/websync#32]
npm install command fails with : 

```
 verbose raw, before any munging watchify
 verbose url resolving [ 'https://registry.npmjs.org/', './watchify' ]
 verbose url resolved https://registry.npmjs.org/watchify
 http GET https://registry.npmjs.org/watchify
 ERR! Error: failed to fetch from registry: ejs
 ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
 ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
 ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
 ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
 ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
 ERR!     at Request.emit (events.js:88:20)
 ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
 ERR!     at ClientRequest.emit (events.js:67:17)
 ERR!     at HTTPParser.onIncoming (http.js:1261:11)
 ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
 ERR! You may report this log at:
 ERR!     <http://bugs.debian.org/npm>
 ERR! or use
 ERR!     reportbug --attach /home/<user>/websync/npm-debug.log npm
 ERR! 
 ERR! System Linux 3.10.23-xxxx-std-ipv6-64
 ERR! command "node" "/usr/bin/npm" "install"
 ERR! cwd /home/<user>/websync
 ERR! node -v v0.6.12
 ERR! npm -v 1.1.4
 ERR! message failed to fetch from registry: ejs
 verbose exit [ 1, true ]
```

username was replaced by <user>

I found this ticket with same error (related to raspberry pi though)
https://bugs.launchpad.net/raspbian/+bug/1480668

**Comment by ZalemCitizen** [comment]
Ok, that was a npm version problem. I had to add repository : 

    curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -

(see http://doc.ubuntu-fr.org/nodejs )
The install could go further but fails after : 

    npm WARN install Couldn't install optional dependency: Unsupported
    npm WARN install Couldn't install optional dependency: Unsupported
    npm ERR! Linux 3.2.0-91-virtual
    npm ERR! argv "node" "/usr/bin/npm" "install"
    npm ERR! node v0.12.7
    npm ERR! npm  v3.3.5
    
    npm ERR! Cannot read property 'localeCompare' of undefined

Maybe another version problem

**Comment by ZalemCitizen** [comment]
New try after updating node.js through npm
New error

    npm WARN install Couldn't install optional dependency: Unsupported
    npm WARN install Couldn't install optional dependency: Unsupported
    npm ERR! Linux 3.2.0-91-virtual
    npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install"
    npm ERR! node v4.0.0
    npm ERR! npm  v3.3.5
    
    npm ERR! Cannot read property 'localeCompare' of undefined

Are you sure you tested install on bare Ubuntu 12.04 ? : p

**Comment by furier** [comment]
Yes I am very sure :P

**Comment by mason105** [comment]
i have these problem too.

**Comment by Mikeambrose3** [comment]
Yeah, doesn't work on basically any distro including newer ones. Always ends up with errors because the install processes uses 2-4 year old dependencies.
