### ISSUE TITLE
Works on centos?

### ISSUE THREAD

**Issue by scorpio2k2** [furier/websync#35]
is this working on centos 6 ?

**Comment by furier** [comment]
Never tried it on Centos X, you are welcome to do so and report back with
the result, even write up a wiki how to for centos 6. :)

søn. 1. nov. 2015 kl. 20.12 skrev Valentin Ciopei <notifications@github.com

**Comment by scorpio2k2** [comment]
I tried but is not working. 
I'm testing ...

**Comment by scorpio2k2** [comment]
I can\t make it work...IF you can help me

**Comment by scorpio2k2** [comment]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
npm WARN optional Skipping failed optional dependency /watchify/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.2.1
