### ISSUE TITLE
Backend Logs

### ISSUE THREAD

**Issue by jack** [furier/websync#36]
The live logging is useful, but is there a way to get Websync to save the logs in the back end? Right now they just disappear once I refresh.

Also, is there a way to run it in a web directory (such as /var/www/html/websync) rather than on port 3000?

**Comment by furier** [comment]
Saving some kind of logging on the backend would be useful and has been thought of just forgotten to create an issue for it here on github, thanks. :)

Regarding the other question, you must use node to run websync. You will not be able to host websync with apache, nginx or any other web server service. On the other hand you can change the port to what ever you want and with e.g nginx you can set up a reverse proxy with url rewrite to make the url become. `websync.jack.com`

**Comment by hradec** [comment]
Can I assume there's no update on this feature? 

If not, if someone points me out where websync actually executes rsync, I can work on it!
