### ISSUE TITLE
Possibility to specify --rsync-path

### ISSUE THREAD

**Issue by mister-bogus** [furier/websync#38]
Using websync between 2 servers, the problem is the remote server is a NAS and rsync is not in the path and it is found in a non-standard location. The option to specify the parameter --rsync-path would be great to solve this case.

**Comment by furier** [comment]
Hmmm, didn't know you could end up in such a situation. Couldn't you add it to the path?

    export PATH=$PATH:/path/to/dir

And symlink to binaries

    cd /usr/bin
    sudo ln -s /path/to/binary binary-name

**Comment by mister-bogus** [comment]
It is in the path (path being set in .bashrc and .profile of the remote host) but not being found anyhow when doing : 
`rsync -ruva --progress --rsh=ssh /dir/to/backup \ root@drobo5n.local.lan:/mnt/DroboFS/Shares/Public`
I get : 
`sh: rsync: not found`

**Comment by furier** [comment]
Rsync is installed, and also created symblink?

fre. 15. jan. 2016 kl. 21.57 skrev mister-bogus <notifications@github.com>:

**Comment by mister-bogus** [comment]
That also works, thanks.The only problem with that is I have to create the symlink every time I reboot the NAS.

**Comment by furier** [comment]
No problem, but what about creating a cron script to create the symblink on
reboot?

søn. 17. jan. 2016 kl. 18.47 skrev mister-bogus <notifications@github.com>:

**Comment by mister-bogus** [comment]
Yeah I will implement something like that, the NAS has a mechanism to start services and programs installed, I will just modify the script that starts rsync to create the symlink. thanks a lot.

**Comment by furier** [comment]
Glad to help! :)
