### ISSUE TITLE
Can't install on Ubuntu 16.04 (either :)), halts at 'node-gyp rebuild'

### ISSUE THREAD

**Issue by loppis** [furier/websync#41]
First of all I want to mention that websync seems to be EXACTLY what I've been searching for quite a while, so it's devastating to find out that it doesn't install in newer ubuntus :(

I'm getting similar errors as what's been reported already :

> npm install
> 363 error Linux 4.4.0-22-generic
> 364 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
> 365 error node v4.2.6
> 366 error npm  v3.5.2
> 367 error code ELIFECYCLE
> 368 error hiredis@0.1.17 install: `node-gyp rebuild`
> 368 error Exit status 1
> 369 error Failed at the hiredis@0.1.17 install script 'node-gyp rebuild'.
> 369 error Make sure you have the latest version of node.js and npm installed.
> 369 error If you do, this is most likely a problem with the hiredis package,
> 369 error not with npm itself.
> 369 error Tell the author that this fails on your system:
> 369 error     node-gyp rebuild
> 369 error You can get information on how to open an issue for this project with:
> 369 error     npm bugs hiredis
> 369 error Or if that isn't available, you can get their info via:
> 369 error     npm owner ls hiredis
> 369 error There is likely additional logging output above.
> 370 verbose exit [ 1, true ]

I 've tried to reinstall nodejs and npm a couple of times without making any progress, I've also tried other suggestions found on google but nothing helped.  Can't think of anything else to try... Truly grateful if anyone has any ideas :) Thank you.

**Comment by furier** [comment]
Try some of the forks or docker containers :)

ons. 1. jun. 2016 kl. 22.59 skrev loppis <notifications@github.com>:

**Comment by praneethkumarpidugu** [comment]
Your machine is trying to interpret node which is actually by defualt node-js so you need to update the binary
$  sudo ln -s /usr/bin/nodejs /usr/bin/node

**Comment by blackyzero** [comment]
got same issue, unable to install on Ubuntu 16.04
any idea or update to fix would be highly appreciated!

**Comment by pabloalbrecht** [comment]
Same here. Looked at the forks and docker containers and nothing works.

**Comment by pabloalbrecht** [comment]
I have tried all the other forks and docker scripts, but this error keeps coming back:
it seems the real problem is Not compatible with your operating system or architecture: fsevents@1.1.1 and fsevents@0.2.1
> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
> npm WARN optional Skipping failed optional dependency /watchify/chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.2.1
> npm WARN restangular@1.6.1 requires a peer of angular@>=1.3.12 but none was installed.
> npm ERR! Linux 3.14.32-xxxx-grs-ipv6-64
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.5.2
> npm ERR! code ELIFECYCLE
> 
> npm ERR! hiredis@0.1.17 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the hiredis@0.1.17 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the hiredis package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs hiredis
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls hiredis
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/forge/websync/npm-debug.log
>
