### ISSUE TITLE
 Error: ENOENT: no such file or directory for $ node server.js

### ISSUE THREAD

**Issue by praneethkumarpidugu** [furier/websync#43]
Looks like its looking for wsdata.json and instead we have default.wsdata.json

**$ node server.js**
Express server listening on port 3000 in development mode
{ Error: ENOENT: no such file or directory, open '/home/ppidugu/Downloads/websync-master/wsdata.json'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/ppidugu/Downloads/websync-master/wsdata.json' }

**Comment by furier** [comment]
cp default.wsdata.json wsdata.json

That should fix it...

**Comment by praneethkumarpidugu** [comment]
I understand this step was mentioned in the gulpfile.js but I wasn't able to reach full execution of gulp...It was a pain from almost two days :(

**Comment by furier** [comment]
Sorry for being so blunt, don't mean to be harsh, even tho thats how it sounds. 

But i'm not maintaining this project anymore and haven't been for years. I can't be expected to step up every time there is an update or every time somebody gets an error. 

If you want to use the project you need to either fork and fix it, and maybe submit a pull request if you want to share it with the rest of the world or don't use it.

**Comment by praneethkumarpidugu** [comment]
@furier I dont know what to say.....I'm a big fan of your project. I dont expect you to be upgrading for every node.js, gulp or other dependencies..I thought If I post few of the issues may be someone could find somilar issues and that would lead to the solution someday......I dont have intention to make you feel bad....sorry if I'm being..

**Comment by furier** [comment]
No problem man :) cool to hear you are a fan of the project, warms my hearth even tho I dont maintain it any more.
