### ISSUE TITLE
ssh-copy-id not working for websync@docker container

### ISSUE THREAD

**Issue by furier** [furier/websync#6]
To investigate the problem I logged on to the websync docker container with [**nsenter**](https://github.com/jpetazzo/nsenter), and tried to use the `ssh-copy-id` command and got the following feedback:

```
/usr/bin/ssh-copy-id: ERROR: No identities found
```

Since I rememberd I had generated a ssh key previously, I went looking for it in `~`, which resulted in:

```
-bash: cd: /home/<username>: No such file or directory
```

hmmm, it sais i'm logged in as `root`...
`/root/.ssh/id_rsa` exists but it didn't try to use that id...

Then I tried specifying the key file with the `ssh-copy-id` command and got another result:

```
mktemp: failed to create file via template '/home/<username>/.ssh/ssh-copy-id_id.XXXXXXXXXX': No such file or directory
mktemp failed
```

creating the directories `/home/<username>/.ssh/` solved the problem, but this is still a problem that needs to be fixed generally.

**Comment by behinddesign** [comment]
sshpass -p 'mypass' ssh-copy-id -o StrictHostKeyChecking=no user@host

https://github.com/furier/websync/blob/master/lib/ssh-copy-id.js#L42

This was the only way I was able to get websync working in a docker environment. By default, sshpass wasn't able to send the password through to ssh-copy-id when it prompts for a fingerprint.

This obviously has it's downsides but without building a UI to confirm the fingerprint, it needs to be skipped.
